apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiscal-finance-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiscal-finance-frontend
  template:
    metadata:
      labels:
        app: fiscal-finance-frontend
    spec:
      containers:
        - name: frontend
          image: viniciusmoraodev/fiscal-finance-frontend:v1.1.6
          imagePullPolicy: Always
          ports:
            - containerPort: 80