apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiscal-finance-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiscal-finance-backend
  template:
    metadata:
      labels:
        app: fiscal-finance-backend
    spec:
      containers:
        - name: backend
          image: viniciusmoraodev/fiscal-finance-backend:v1.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"