apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-platform-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-platform-frontend
  template:
    metadata:
      labels:
        app: devops-platform-frontend
    spec:
      containers:
        - name: frontend
          image: viniciusmoraodev/devops-platform-frontend:v5.0.2
          ports:
            - containerPort: 80