apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-leads-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-leads-backend
  template:
    metadata:
      labels:
        app: crm-leads-backend
    spec:
      containers:
        - name: backend
          image: viniciusmoraodev/crm-leads-backend:v2.4.12
          imagePullPolicy: Always
          ports:
            - containerPort: 3031
          env:
            - name: NODE_ENV
              value: "production"