apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: viniciusmoraodev/core-engine-backend:v1.1.22
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://admin:admin123@postgres:5432/erp_core?schema=public"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: JWT_SECRET
              value: "super-secret-key-change-in-production"
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
