apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-engine-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-engine-backend
  template:
    metadata:
      labels:
        app: core-engine-backend
    spec:
      containers:
        - name: core-engine-backend
          image: viniciusmoraodev/core-engine-backend:v1.2.22
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: core-engine-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: core-engine-secrets
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: core-engine-secrets
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
