apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-engine
  template:
    metadata:
      labels:
        app: core-engine
    spec:
      containers:
        - name: core-engine
          image: viniciusmoraodev/core-engine:v1.0.23
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            #Lucas mudou aqui
            - name: DATABASE_URL
              value: "postgresql://admin:admin123@40.82.176.176:5433/erp_core"
            - name: REDIS_URL
              value: "redis://http://40.82.176.176/:6379"
            - name: JWT_SECRET
              value: "super-secret-key-change-in-production"
