apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-engine-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-engine-frontend
  template:
    metadata:
      labels:
        app: core-engine-frontend
    spec:
      containers:
        - name: frontend
          image: viniciusmoraodev/core-engine-frontend:v1.2.16
          imagePullPolicy: Always
          ports:
            - containerPort: 80
